apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-flow-master
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: flow-master
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-flow-master
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true